name: test

# FIXME only run on master when done testing
on:
  push:
    branches: [ master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        os: [macos-11.0, macos-10.15]
    steps:
    - name: Downloading miniconda
      run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - name: Installing miniconda
      run: chmod +x Miniconda3-latest-MacOSX-x86_64.sh && bash Miniconda3-latest-MacOSX-x86_64.sh -p python -b -f
    - name: Source venv
      run: source python/bin/activate
    - name: Init conda
      run: conda init zsh
    - name: Create venv
      run: conda create -y -n test_venv python=3.6
    - name: Activate venv
      run: conda activate test_venv
    - name: Verify venv
      run: python --version